"""add_research_session_tables

Revision ID: 3e5089f32f9a
Revises: 
Create Date: 2026-04-04 22:56:26.138495

"""
from typing import Sequence, Union

import sqlalchemy as sa

import src.infrastructure.persistence
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3e5089f32f9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=False),
    sa.Column('processing_timestamp', sa.DateTime(), nullable=False),
    sa.Column('objective', sa.String(length=255), nullable=True),
    sa.Column('raw_text_size', sa.Integer(), nullable=False),
    sa.Column('entities_extracted_count', sa.Integer(), nullable=False),
    sa.Column('process_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='process_status_enum', native_enum=False), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quality_score >= 0 AND quality_score <= 1', name='ck_documents_quality_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file')
    )
    op.create_index('idx_documents_file', 'documents', ['source_file'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['process_status'], unique=False)
    op.create_index('idx_documents_timestamp', 'documents', ['processing_timestamp'], unique=False)
    op.create_table('relationship_types',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('relationship_name', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('composition', 'therapeutic', 'property', 'similarity', 'other', name='relationship_category_enum', native_enum=False), nullable=True),
    sa.Column('confidence_baseline', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence_baseline >= 0 AND confidence_baseline <= 1', name='ck_relationship_types_confidence_baseline'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_name'),
    sa.UniqueConstraint('relationship_type')
    )
    op.create_index('idx_rel_types_name', 'relationship_types', ['relationship_name'], unique=False)
    op.create_index('idx_rel_types_type', 'relationship_types', ['relationship_type'], unique=False)
    op.create_table('research_results',
    sa.Column('cycle_id', sa.String(length=128), nullable=False),
    sa.Column('cycle_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('current_phase', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('research_objective', sa.Text(), nullable=True),
    sa.Column('research_scope', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('outcomes_json', sa.Text(), nullable=False),
    sa.Column('deliverables_json', sa.Text(), nullable=False),
    sa.Column('quality_metrics_json', sa.Text(), nullable=False),
    sa.Column('risk_assessment_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('persisted_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('cycle_id')
    )
    op.create_index('idx_research_results_persisted_at', 'research_results', ['persisted_at'], unique=False)
    op.create_index('idx_research_results_status', 'research_results', ['status'], unique=False)
    op.create_table('research_sessions',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('cycle_id', sa.String(length=128), nullable=False),
    sa.Column('cycle_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'completed', 'failed', 'suspended', name='session_status_enum', native_enum=False), nullable=False),
    sa.Column('current_phase', sa.String(length=64), nullable=True),
    sa.Column('research_objective', sa.Text(), nullable=True),
    sa.Column('research_scope', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('researchers_json', sa.Text(), nullable=False),
    sa.Column('advisors_json', sa.Text(), nullable=False),
    sa.Column('resources_json', sa.Text(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('timeline_json', sa.Text(), nullable=False),
    sa.Column('quality_metrics_json', sa.Text(), nullable=False),
    sa.Column('risk_assessment_json', sa.Text(), nullable=False),
    sa.Column('expert_reviews_json', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('categories_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rs_created', 'research_sessions', ['created_at'], unique=False)
    op.create_index('idx_rs_status', 'research_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_research_sessions_cycle_id'), 'research_sessions', ['cycle_id'], unique=True)
    op.create_table('entities',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('document_id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('formula', 'herb', 'syndrome', 'efficacy', 'property', 'taste', 'meridian', 'other', name='entity_type_enum', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('alternative_names', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_entities_confidence'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entities_document', 'entities', ['document_id'], unique=False)
    op.create_index('idx_entities_name', 'entities', ['name'], unique=False)
    op.create_index('idx_entities_type', 'entities', ['type'], unique=False)
    op.create_table('phase_executions',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('session_id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='phase_status_enum', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pe_session_phase', 'phase_executions', ['session_id', 'phase'], unique=False)
    op.create_table('processing_logs',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('document_id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('start', 'success', 'failure', 'warning', name='log_status_enum', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_statistics',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('document_id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('formulas_count', sa.Integer(), nullable=False),
    sa.Column('herbs_count', sa.Integer(), nullable=False),
    sa.Column('syndromes_count', sa.Integer(), nullable=False),
    sa.Column('efficacies_count', sa.Integer(), nullable=False),
    sa.Column('relationships_count', sa.Integer(), nullable=False),
    sa.Column('graph_nodes_count', sa.Integer(), nullable=False),
    sa.Column('graph_edges_count', sa.Integer(), nullable=False),
    sa.Column('graph_density', sa.Float(), nullable=False),
    sa.Column('connected_components', sa.Integer(), nullable=False),
    sa.Column('source_modules', sa.JSON(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('quality_metrics',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('document_id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('entity_precision', sa.Float(), nullable=False),
    sa.Column('relationship_precision', sa.Float(), nullable=False),
    sa.Column('graph_quality_score', sa.Float(), nullable=False),
    sa.Column('evaluation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('evaluator', sa.String(length=100), nullable=True),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('research_analyses',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('document_id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('research_perspectives', sa.JSON(), nullable=False),
    sa.Column('formula_comparisons', sa.JSON(), nullable=False),
    sa.Column('herb_properties_analysis', sa.JSON(), nullable=False),
    sa.Column('pharmacology_integration', sa.JSON(), nullable=False),
    sa.Column('network_pharmacology', sa.JSON(), nullable=False),
    sa.Column('supramolecular_physicochemistry', sa.JSON(), nullable=False),
    sa.Column('knowledge_archaeology', sa.JSON(), nullable=False),
    sa.Column('complexity_dynamics', sa.JSON(), nullable=False),
    sa.Column('research_scoring_panel', sa.JSON(), nullable=False),
    sa.Column('summary_analysis', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('entity_relationships',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('source_entity_id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('target_entity_id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('relationship_type_id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_by_module', sa.String(length=100), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('relationship_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_entity_relationships_confidence'),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['relationship_types.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rel_source', 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index('idx_rel_target', 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_index('idx_rel_type', 'entity_relationships', ['relationship_type_id'], unique=False)
    op.create_table('research_artifacts',
    sa.Column('id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('session_id', src.infrastructure.persistence.GUID(), nullable=False),
    sa.Column('phase_execution_id', src.infrastructure.persistence.GUID(), nullable=True),
    sa.Column('artifact_type', sa.Enum('paper', 'dataset', 'analysis', 'hypothesis', 'report', 'visualization', 'reference', 'other', name='artifact_type_enum', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phase_execution_id'], ['phase_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ra_session', 'research_artifacts', ['session_id'], unique=False)
    op.create_index('idx_ra_type', 'research_artifacts', ['artifact_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ra_type', table_name='research_artifacts')
    op.drop_index('idx_ra_session', table_name='research_artifacts')
    op.drop_table('research_artifacts')
    op.drop_index('idx_rel_type', table_name='entity_relationships')
    op.drop_index('idx_rel_target', table_name='entity_relationships')
    op.drop_index('idx_rel_source', table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_table('research_analyses')
    op.drop_table('quality_metrics')
    op.drop_table('processing_statistics')
    op.drop_table('processing_logs')
    op.drop_index('idx_pe_session_phase', table_name='phase_executions')
    op.drop_table('phase_executions')
    op.drop_index('idx_entities_type', table_name='entities')
    op.drop_index('idx_entities_name', table_name='entities')
    op.drop_index('idx_entities_document', table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_research_sessions_cycle_id'), table_name='research_sessions')
    op.drop_index('idx_rs_status', table_name='research_sessions')
    op.drop_index('idx_rs_created', table_name='research_sessions')
    op.drop_table('research_sessions')
    op.drop_index('idx_research_results_status', table_name='research_results')
    op.drop_index('idx_research_results_persisted_at', table_name='research_results')
    op.drop_table('research_results')
    op.drop_index('idx_rel_types_type', table_name='relationship_types')
    op.drop_index('idx_rel_types_name', table_name='relationship_types')
    op.drop_table('relationship_types')
    op.drop_index('idx_documents_timestamp', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_file', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
