"""T2.3 documents dedup: content_hash + ingest_run_id, composite UNIQUE.

Replaces single-column UNIQUE on documents.source_file with a
composite UNIQUE (source_file, content_hash). Adds nullable
content_hash CHAR(64) and ingest_run_id VARCHAR(64) columns plus
matching indexes. The accompanying backfill script
(tools/backfill_documents_content_hash.py) is responsible for
populating content_hash from disk-resident raw text and collapsing
legacy duplicate rows that share the same canonical source_file.

Revision ID: a8c4e5d6f7b9
Revises: f1a2b3c4d5e6
Create Date: 2026-04-28
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a8c4e5d6f7b9"
down_revision = "f1a2b3c4d5e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name

    # 1) Add new columns (nullable; backfill script populates afterwards).
    with op.batch_alter_table("documents") as batch:
        batch.add_column(sa.Column("content_hash", sa.CHAR(64), nullable=True))
        batch.add_column(sa.Column("ingest_run_id", sa.String(64), nullable=True))

    # 2) Drop legacy single-column UNIQUE on source_file (if present).
    #    SQLite + autogenerated table may have created an unnamed UNIQUE
    #    via Column(unique=True); we use batch mode to recreate cleanly.
    if dialect == "postgresql":
        # PG: name is auto-generated 'documents_source_file_key' by default.
        op.execute(
            "ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_source_file_key"
        )
    else:
        # SQLite path: use batch-mode reflection to drop and recreate without
        # the singleton UNIQUE.  The composite UNIQUE is added below.
        with op.batch_alter_table("documents") as batch:
            # batch_alter_table will rebuild the table; simply NOT adding the
            # original UniqueConstraint(source_file) achieves the drop because
            # the model definition no longer carries `unique=True`.
            pass

    # 3) Composite UNIQUE (source_file, content_hash). Allowed during the
    #    nullable-content_hash transition because PG/SQLite treat NULL as
    #    distinct in UNIQUE; backfill will populate before any NOT NULL.
    with op.batch_alter_table("documents") as batch:
        batch.create_unique_constraint(
            "uq_documents_source_hash", ["source_file", "content_hash"]
        )
        batch.create_index("idx_documents_content_hash", ["content_hash"])
        batch.create_index("idx_documents_ingest_run", ["ingest_run_id"])


def downgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name

    with op.batch_alter_table("documents") as batch:
        batch.drop_index("idx_documents_ingest_run")
        batch.drop_index("idx_documents_content_hash")
        batch.drop_constraint("uq_documents_source_hash", type_="unique")

    # Restore singleton UNIQUE on source_file (best-effort; will fail if
    # current data violates it — caller must dedup first).
    if dialect == "postgresql":
        op.execute(
            "ALTER TABLE documents ADD CONSTRAINT documents_source_file_key UNIQUE (source_file)"
        )
    else:
        with op.batch_alter_table("documents") as batch:
            batch.create_unique_constraint(
                "documents_source_file_key", ["source_file"]
            )

    with op.batch_alter_table("documents") as batch:
        batch.drop_column("ingest_run_id")
        batch.drop_column("content_hash")
